#!/usr/bin/env bash
set -eu
log-prefix() { sed -u "s/^/$1/"; }

for feed_id in $(keeper config feedbase feeds | jshon -k); do
  echo "Starting update loop for feed #$feed_id..."
  keeper feedbase-update-loop $feed_id |& log-prefix "[#$feed_id] " &
  sleep 2
done

wait
