#!/bin/sh
cat <<.
Usage: keeper <command> [<args>]

Commands:

   ls            list all available Keeper services
   ps            list currently running Keeper services
   start         start the specified services (default: all)
   stop          stop the specified services (default: all)
   restart       restart the specified services (default: all)
   logs          view logs for the specified services (default: all)
   price         fetch price quote for the specified pair

Report bugs at <https://github.com/nexusdev/keeper/issues/new>.
.
