#!/usr/bin/env bash
set -eu
fail() { echo >&2 "${0##*/}: error: $*"; exit 1; }

[[ $# = 3 ]] || { echo "Usage: ${0##*/} <a> <b> <number>"; exit 1; }
a=$1 b=$2 number=$3

hex_char_count=$(((a + b) / 4))
((a % 8 == 0 && b % 8 == 0)) ||
fail "both parts must be divisible by 8: ${a}x${b}"

echo "obase = 16; scale = 0; ($number * 2 ^ $b) / 1" | bc |
printf "0x%${hex_char_count}s\n" "$(cat)" | tr ' ' 0
